version: '3'
services:
  db:
    image: postgres

  web:
    environment:
      - RACK_ENV=development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=
      - DATABASE_HOST=db

    build: .
    ports:
      - "3000:3000"
        # command: bundle exec rails s -b '0.0.0.0'
    depends_on:
      - db

        #options:
        #  logging:
        #    driver: awslogs
        #    options:
        #      awslogs-group: grabat-personal
        #      awslogs-region: ap-northeast-1
        #      awslogs-stream-prefix: grabat-personal
