version: '2'
services:
  web:
    environment:
      - RACK_ENV=development
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_HOST=qsyoku-dev.ctoswy67aayg.ap-northeast-1.rds.amazonaws.com
    image: 105137413805.dkr.ecr.ap-northeast-1.amazonaws.com/9syoku:latest
    cpu_shares: 100
    logging:
      driver: awslogs
      options:
        awslogs-group: grabat-personal
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: grabat-personal
